Remove the unused functionality from passmenu

diff --git a/.local/bin/passmenu b/.local/bin/passmenu
--- a/.local/bin/passmenu
+++ b/.local/bin/passmenu
@@ -1,21 +1,10 @@
 #!/usr/bin/env bash
 shopt -s nullglob globstar
 
-typeit=0
-
-if [[ $1 == "--type" ]]; then
-  typeit=1
-  shift
-fi
-
-if [[ -n ${WAYLAND_DISPLAY} ]]; then
-  dmenu="dmenu-wl"
-  xdotool="ydotool type --file -"
-elif [[ -n ${DISPLAY} ]]; then
+if [ -n ${DISPLAY} ]; then
   dmenu=dmenu
-  xdotool="xdotool type --clearmodifiers --file -"
 else
-  printf 'Error: No Wayland or X11 display detected\n' >&2
+  printf 'Error: No X11 display detected\n' >&2
   exit 1
 fi
 
@@ -25,11 +14,6 @@ password_files=( "${password_files[@]#"${prefix}"/}" )
 password_files=( "${password_files[@]%.gpg}" )
 
 password=$(printf '%s\n' "${password_files[@]}" | "${dmenu}" "$@")
+[ -n ${password} ] || exit
 
-[[ -n ${password} ]] || exit
-
-if [[ ${typeit} -eq 0 ]]; then
-  pass show -c "${password}" 2>/dev/null
-else
-  pass show "${password}" | { IFS= read -r pass; printf '%s' "${pass}"; } | ${xdotool}
-fi
+pass show -c "${password}" 2>/dev/null
