Replace echo by printf

diff --git a/.local/bin/passmenu b/.local/bin/passmenu
--- a/.local/bin/passmenu
+++ b/.local/bin/passmenu
@@ -15,7 +15,7 @@ elif [[ -n ${DISPLAY} ]]; then
 	dmenu=dmenu
 	xdotool="xdotool type --clearmodifiers --file -"
 else
-	echo "Error: No Wayland or X11 display detected" >&2
+	printf 'Error: No Wayland or X11 display detected\n' >&2
 	exit 1
 fi
 
@@ -31,5 +31,5 @@ password=$(printf '%s\n' "${password_files[@]}" | "${dmenu}" "$@")
 if [[ ${typeit} -eq 0 ]]; then
 	pass show -c "${password}" 2>/dev/null
 else
-	pass show "${password}" | { IFS= read -r pass; printf %s "${pass}"; } | ${xdotool}
+	pass show "${password}" | { IFS= read -r pass; printf '%s' "${pass}"; } | ${xdotool}
 fi
