Replace tabs by spaces

diff --git a/.local/bin/passmenu b/.local/bin/passmenu
--- a/.local/bin/passmenu
+++ b/.local/bin/passmenu
@@ -4,19 +4,19 @@ shopt -s nullglob globstar
 typeit=0
 
 if [[ $1 == "--type" ]]; then
-	typeit=1
-	shift
+  typeit=1
+  shift
 fi
 
 if [[ -n ${WAYLAND_DISPLAY} ]]; then
-	dmenu="dmenu-wl"
-	xdotool="ydotool type --file -"
+  dmenu="dmenu-wl"
+  xdotool="ydotool type --file -"
 elif [[ -n ${DISPLAY} ]]; then
-	dmenu=dmenu
-	xdotool="xdotool type --clearmodifiers --file -"
+  dmenu=dmenu
+  xdotool="xdotool type --clearmodifiers --file -"
 else
-	printf 'Error: No Wayland or X11 display detected\n' >&2
-	exit 1
+  printf 'Error: No Wayland or X11 display detected\n' >&2
+  exit 1
 fi
 
 prefix=${PASSWORD_STORE_DIR-~/.password-store}
@@ -29,7 +29,7 @@ password=$(printf '%s\n' "${password_files[@]}" | "${dmenu}" "$@")
 [[ -n ${password} ]] || exit
 
 if [[ ${typeit} -eq 0 ]]; then
-	pass show -c "${password}" 2>/dev/null
+  pass show -c "${password}" 2>/dev/null
 else
-	pass show "${password}" | { IFS= read -r pass; printf '%s' "${pass}"; } | ${xdotool}
+  pass show "${password}" | { IFS= read -r pass; printf '%s' "${pass}"; } | ${xdotool}
 fi
