Simplify the synchronization script

diff --git a/.local/bin/synner b/.local/bin/synner
--- a/.local/bin/synner
+++ b/.local/bin/synner
@@ -1,5 +1,5 @@
-#!/usr/bin/env bash
-set -uf -o pipefail
+#!/bin/sh
+set -euf
 
 
 usage="Usage: $(basename "$0") [<commit-message>]
@@ -14,8 +14,7 @@ inside the synchronized directory."
 
 
 synced_dir="${HOME}/notes"
-git_commit_msg="Sync"
-git_dir=""
+commit_msg="Sync"
 
 
 die() {
@@ -23,88 +22,49 @@ die() {
   exit 1
 }
 
-set_git() {
-  git_dir="${1%/*}"
-
-  while [[ ! -d "${git_dir}" && "${git_dir%/*}/" == "${synced_dir%/}/"* ]]; do
-    git_dir="${git_dir%/*}"
-  done
-
-  [[ $(git -C "${git_dir}" rev-parse --is-inside-work-tree 2>/dev/null) \
-    == true ]] || git_dir=""
-}
-
 cmd_git() {
-  set_git "${synced_dir}/"
-
-  if [[ "$1" == "init" ]]; then
-    git_dir="${synced_dir}"
-    git -C "${git_dir}" "$@" || exit 1
-    git_add "${synced_dir}"
-    git_commit "Initialize the repository"
-  elif [[ -n "${git_dir}" ]]; then
-    git -C "${git_dir}" "$@"
+  if [ "$1" = "init" ]; then
+    mkdir -p "${synced_dir}"
+    git -C "${synced_dir}" "$@"
+    git -C "${synced_dir}" add -A
+    git -C "${synced_dir}" commit -m "Initialize the repository"
+  elif [ "$(git -C "${synced_dir}" rev-parse --is-inside-work-tree \
+          2> /dev/null)" = true ]; then
+    git -C "${synced_dir}" "$@"
   else
     die "Error: Git repository not initialized."
   fi
 }
 
-git_add() {
-  [[ -n "${git_dir}" ]] || return
-  git -C "${git_dir}" add "$1" || return
-  [[ -n $(git -C "${git_dir}" status --porcelain "$1") ]] || return
-}
 
-git_commit() {
-  [[ -n "${git_dir}" ]] || return
-  git -C "${git_dir}" commit -m "$1"
-}
+# Show usage.
+if [ "$#" -gt 0 ] && [ "$1" = "-h" ]; then
+  echo "${usage}"
+  exit 0
+fi
 
-git_pull() {
-  [[ -n "${git_dir}" ]] || return
-  git -C "${git_dir}" pull
-}
+# Check whether the directory exists.
+if [ ! -d "${synced_dir}" ]; then
+  die "Error: The directory ${synced_dir} does not exist."
+fi
 
-git_push() {
-  [[ -n "${git_dir}" ]] || return
-  git -C "${git_dir}" push
-}
+# Parse arguments.
+if [ "$#" -gt 0 ]; then
+  case "$1" in
+    # Invoke git with the rest of the arguments.
+    git) shift; cmd_git "$@"; exit "$?" ;;
+    # Assume that the first argument is a commit message.
+    *) commit_msg="$1" ;;
+  esac
+fi
 
-main() {
-  local commit_msg="${git_commit_msg}"
+# Check whether sync is necessary.
+if [ -z "$(git -C "${synced_dir}" status --porcelain)" ]; then
+  exit 0
+fi
 
-  # Show usage.
-  if [[ "$#" -gt 0 && "$1" == "-h" ]]; then
-    echo "${usage}"
-    exit 0
-  fi
-
-  # Check whether the directory exists.
-  if [[ ! -d "${synced_dir}" ]]; then
-    die "Error: The directory ${synced_dir} does not exist."
-  fi
-
-  # Check whether the git repository is initialized.
-  git -C "${synced_dir}" rev-parse 2>/dev/null \
-    || die "Error: Git repository not initialized."
-
-  # Parse arguments.
-  if [[ "$#" -gt 0 ]]; then
-    case "$1" in
-      # Invoke git with the rest of the arguments.
-      git) shift; cmd_git "$@"; exit "$?" ;;
-      # Assume that the first argument is a commit message.
-      *) commit_msg="$1" ;;
-    esac
-  fi
-
-  # Synchronize.
-  set_git "${synced_dir}/"
-  git_add "${synced_dir}"
-  git_commit "${commit_msg}"
-  git_pull
-  git_push
-}
-
-
-main "$@"
+# Synchronize.
+cmd_git add -A
+cmd_git commit -m "${commit_msg}"
+cmd_git pull
+cmd_git push
